language: go
go:
  - "1.11.x"
env:
  - GO111MODULE=on
before_install:
  - curl https://raw.githubusercontent.com/go-task/task/master/install-task.sh | sh
  - mv ./bin/task $GOPATH/bin
install:
  - task module
script:
  - task test
before_deploy:
  - task dist
deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
