on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          curl -sL https://taskfile.dev/install.sh | sh
          sudo mv bin/task /usr/local/bin
          curl -L -O https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
          tar zxvf ghr_v0.13.0_linux_amd64.tar.gz
          sudo mv ghr_v0.13.0_linux_amd64/ghr /usr/local/bin

      - name: Upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: task github-release

      - name: Build container
        run: task build-container

      - name: Docker Login
        run: docker login -u summerwind -p ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Push container
        run: task push-release-container
